<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [1]:
def matrix_mul():

    p=int(input("enter the number of rows in A: "))
    n=int(input('enter the number of column in A or number of rows in B: '))
    q=int(input('enter number of column in B: '))

    A=[[int(input('Enter the element in A:'))for i in range(n)]for j in range(p)]
    B=[[int(input('Enter the element in B:'))for i in range(q)]for j in range(n)]

    #print(mat1)
    #print(mat2)

    result=[[0 for i in range(q)] for j in range(p)]
    result1=[]
    for i in range(p):
        for j in range(q):
            for k in range(n):
                result[i][j]=result[i][j]+A[i][k]*B[k][j]
    print()        
    print("Multiplication of A and B:")
            
    for i in range(p):
        for j in range(q):
            print(format(result[i][j],"<4"),end="")
        print()
        
matrix_mul()

enter the number of rows in A: 3
enter the number of column in A or number of rows in B: 3
enter number of column in B: 3
Enter the element in A:1
Enter the element in A:3
Enter the element in A:4
Enter the element in A:2
Enter the element in A:5
Enter the element in A:7
Enter the element in A:5
Enter the element in A:9
Enter the element in A:6
Enter the element in B:1
Enter the element in B:0
Enter the element in B:0
Enter the element in B:0
Enter the element in B:1
Enter the element in B:0
Enter the element in B:0
Enter the element in B:0
Enter the element in B:1

Multiplication of A and B:
1   3   4   
2   5   7   
5   9   6   


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [2]:
from random import uniform
import random
def pick_a_number_from_list(A):
    sum_A=0
    cum_sum=[]
    for i in range(len(A)):
        sum_A = sum_A + A[i]
        cum_sum.append(sum_A)
    #print(cum_sum) 
    r=int(random.uniform(0,sum_A))
    #print(r)
    num=0
    for i in range(len(cum_sum)):
        if(r>=cum_sum[i] and r<cum_sum[i+1]):
            return A[i+1]
    return num

def sampling_based_on_magnitued():
    A=[0,5,27,6,13,28,100,45,10,79]
    dic=dict()
    #A.sort()
    #print(A,sum(A))
    for i in range(1,100):
        num=pick_a_number_from_list(A)
        #print(number)
        if num not in dic:
            dic[num]=1
        else:
            dic[num]+=1
    print(dic)

sampling_based_on_magnitued()


{79: 31, 100: 26, 45: 19, 28: 8, 13: 2, 27: 8, 5: 2, 6: 2, 10: 1}


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [3]:
import re

string=str(input("Enter the string:"))

def replace_digits(string): 
    a='#'*len(re.sub('\D','',string))
    return a

print("Input string:",string,'    Output:',replace_digits(string))


Enter the string:ab2c34#
Input string: ab2c34#     Output: ###


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [4]:
def display_dash_board(Students,Marks):
    dictionary = dict(zip(Students,Marks))
    #print('Student_Mark_dict:',dictionary,'\n')
    sort_dict=sorted(dictionary.items(),key=lambda item: item[1],reverse=True)
    print('a.Students Who got top 5 ranks, in the descending order of marks;\n')
    for i in range(len(sort_dict)):
        print(sort_dict[i])
        if i>4:
            break
    print("\n")        

    sort_dict=sorted(dictionary.items(),key=lambda item: item[1])
    print('b.Students Who got least 5 ranks, in the increasing order of marks;\n')
    for i in range(len(sort_dict)):
        print(sort_dict[i])
        if i>3:
            break

    print('\n')
    print('c.student Who got marks between >25th percentile <75th percentile, in the increasing order of marks;\n')
    sort_dict=sorted(dictionary.items(),key=lambda item: item[1],reverse=True)
    Sort_Marks=sorted(Marks,reverse=True)

    max=Sort_Marks[0]
    min=Sort_Marks[-1]
    diff = max - min
    pre_25 = diff*0.25
    pre_75 = diff*0.75

    for i in range(len(sort_dict)):
        for j in range(1,2):
            if sort_dict[i][j]>pre_25 and sort_dict[i][j]<pre_75:
                print(sort_dict[i])
                break
                
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80]

display_dash_board(Students,Marks)

a.Students Who got top 5 ranks, in the descending order of marks;

('student8', 98)
('student10', 80)
('student2', 78)
('student5', 48)
('student1', 45)
('student7', 45)


b.Students Who got least 5 ranks, in the increasing order of marks;

('student3', 12)
('student4', 14)
('student9', 35)
('student6', 43)
('student1', 45)


c.student Who got marks between >25th percentile <75th percentile, in the increasing order of marks;

('student5', 48)
('student1', 45)
('student7', 45)
('student6', 43)
('student9', 35)


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [5]:
import math
S=[(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P=[3,-4]

def closest_points_to_p(S, P):
    d=[]
    for i in range(len(S)):
        for j in range(1):
            a=(S[i][0]*P[0])+(S[i][1])*P[1]
            b=math.sqrt((S[i][0]**2)+(S[i][1]**2))*math.sqrt((P[0]**2)+(P[1]**2))
            c=a/b
            d.append(math.acos(c))
    #print(d)   
    dic= dict(zip(S,d))
    #print(dic)
    sort_dic=sorted(dic.items(),key=lambda item: item[1])     
    #print('sort_dic;',sort_dic)

    for i in range(len(sort_dic)):
        for j in range(1):
            if i>4:
                break
            print(sort_dic[i][j])
            
print('output')
closest_points_to_p(S, P)

output
(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [6]:
import math

def i_am_the_one(R,B,line):
    
    R_rightside=False
    
    line_output_R=[]
    for i in range(len(R)):
        for j in range(1):
            a=eval(line.replace('x','*%s'%R[i][j]).replace('y','*%s'%R[i][j+1]))
            line_output_R.append(a)
            
    for i in line_output_R:
        if i<=0:
            R_rightside=False
            break
            
    else:
        R_rightside=True
        
    B_leftside=False
    
    line_output_B=[]
    for i in range(len(B)):
        for j in range(1):
            b=eval(line.replace('x','*%s'%B[i][j]).replace('y','*%s'%B[i][j+1]))
            line_output_B.append(b)
            
    for i in line_output_B:
        if i>=0:
            B_leftside=False
            break
    else:
        B_leftside=True
        
    if R_rightside and B_leftside:
        return'YES'  
    else:
        return'NO'
        
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no)

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [7]:
def curve_smoothing(string):
    int_index=[]
    New_str_list=string.split(',')
    for i in range(len(New_str_list)):
        if New_str_list[i]!='_':
            int_index.append(i)
    int_index.append(len(New_str_list)-1)
    
    j=0
    for i in int_index:
        num = int(New_str_list[i]) if New_str_list[i] != '_' else 0
        num += int(New_str_list[j]) if New_str_list[j] != '_' and j!=i else 0
        
        num1=num//(i-j+1)
        
        New_str_list=[num1 if j<=k<=i else New_str_list[k] for k in range(len(New_str_list))]
        
        j=i
    return New_str_list
    

S=["_,_,30,_,_,_,50,_,_","_,_,_,24","40,_,_,_,60","80,_,_,_,_"]

for i in range(len(S)):
    print(curve_smoothing(S[i]))
    

[10, 10, 12, 12, 12, 12, 4, 4, 4]
[6, 6, 6, 6]
[20, 20, 20, 20, 20]
[16, 16, 16, 16, 16]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [8]:
def compute_conditional_probabilites(A):
    n=0
    m=0
    for i in range(len(A)):
        for j in range(1):
            if A[i][j]+A[i][j+1]==A[0][0]+A[0][1]:
                n+=1
            if A[i][j+1]==A[0][1]:
                m+=1
    print('a. P(F=F1|S==S1)=',n/m,end="")
    
    a=0
    b=0
    for i in range(len(A)):
        for j in range(1):
            if A[i][j]+A[i][j+1]==A[3][0]+A[3][1]:
                a+=1
            if A[i][j+1]==A[1][1]:
                b+=1
    print(', P(F=F1|S==S2)=',a/b,end="")
    
    c=0
    d=0
    for i in range(len(A)):
        for j in range(1):
            if A[i][j]+A[i][j+1]==0:
                c+=1
            if A[i][j+1]==A[2][1]:
                d+=1
    print(', P(F=F1|S==S3)=',c/d)
    
    e=0
    f=0
    for i in range(len(A)):
        for j in range(1):
            if A[i][j]+A[i][j+1]==A[6][0]+A[6][1]:
                e+=1
            if A[i][j+1]==A[0][1]:
                f+=1
    print('b. P(F=F2|S==S1)=',e/f,end="")
    
    g=0
    h=0
    for i in range(len(A)):
        for j in range(1):
            if A[i][j]+A[i][j+1]==A[1][0]+A[1][1]:
                g+=1
            if A[i][j+1]==A[1][1]:
                h+=1
    print(', P(F=F2|S==S2)=',g/h,end="")
    
    k=0
    l=0
    for i in range(len(A)):
        for j in range(1):
            if A[i][j]+A[i][j+1]==A[4][0]+A[4][1]:
                k+=1
            if A[i][j+1]==A[2][1]:
                l+=1
    print(', P(F=F2|S==S3)=',k/l)
    
    o=0
    p=0
    for i in range(len(A)):
        for j in range(1):
            if A[i][j]+A[i][j+1]==0:
                o+=1
            if A[i][j+1]==A[0][1]:
                p+=1
    print('c. P(F=F3|S==S1)=',o/p,end="")

    q=0
    r=0
    for i in range(len(A)):
        for j in range(1):
            if A[i][j]+A[i][j+1]==A[5][0]+A[5][1]:
                q+=1
            if A[i][j+1]==A[1][1]:
                r+=1
    print(', P(F=F3|S==S2)=',q/r,end="")
    
    s=0
    t=0
    for i in range(len(A)):
        for j in range(1):
            if A[i][j]+A[i][j+1]==A[2][0]+A[2][1]:
                s+=1
            if A[i][j+1]==A[2][1]:
                t+=1
    print(', P(F=F3|S==S3)=',s/t)
    
    u=0
    v=0
    for i in range(len(A)):
        for j in range(1):
            if A[i][j]+A[i][j+1]==A[7][0]+A[7][1]:
                u+=1
            if A[i][j+1]==A[0][1]:
                v+=1
    print('d. P(F=F4|S==S1)=',u/v,end="")
    
    w=0
    x=0
    for i in range(len(A)):
        for j in range(1):
            if A[i][j]+A[i][j+1]==0:
                w+=1
            if A[i][j+1]==A[1][1]:
                x+=1
    print(', P(F=F4|S==S2)=',w/x,end="")
    
    y=0
    z=0
    for i in range(len(A)):
        for j in range(1):
            if A[i][j]+A[i][j+1]==A[8][0]+A[8][1]:
                y+=1
            if A[i][j+1]==A[2][1]:
                z+=1
    print(', P (F=F4|S==S3)=',y/z)
    
    B=0
    C=0
    for i in range(len(A)):
        for j in range(1):
            if A[i][j]+A[i][j+1]==A[9][0]+A[9][1]:
                B+=1
            if A[i][j+1]==A[0][1]:
                C+=1
    print('e. P(F=F5|S==S1)=',B/C,end="")
    
    D=0
    E=0
    for i in range(len(A)):
        for j in range(1):
            if A[i][j]+A[i][j+1]==0:
                D+=1
            if A[i][j+1]==A[1][1]:
                E+=1
    print(', P(F=F5|S==S2)=',D/E,end="")
    
    F=0
    G=0
    for i in range(len(A)):
        for j in range(1):
            if A[i][j]+A[i][j+1]==0:
                F+=1
            if A[i][j+1]==A[2][1]:
                G+=1
    print(', P(F=F5|S==S3)=',F/G,end="")

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

a. P(F=F1|S==S1)= 0.25, P(F=F1|S==S2)= 0.3333333333333333, P(F=F1|S==S3)= 0.0
b. P(F=F2|S==S1)= 0.25, P(F=F2|S==S2)= 0.3333333333333333, P(F=F2|S==S3)= 0.3333333333333333
c. P(F=F3|S==S1)= 0.0, P(F=F3|S==S2)= 0.3333333333333333, P(F=F3|S==S3)= 0.3333333333333333
d. P(F=F4|S==S1)= 0.25, P(F=F4|S==S2)= 0.0, P (F=F4|S==S3)= 0.3333333333333333
e. P(F=F5|S==S1)= 0.25, P(F=F5|S==S2)= 0.0, P(F=F5|S==S3)= 0.0

<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [9]:
def string_features(S1, S2):
    S1_set=set(S1.split())
    
    S2_set=set(S2.split())
    
    A=print('a.',len(S1_set & S2_set))
    B=print('b.',list(S1_set - S2_set))
    C=print('c.',list(S2_set - S1_set))
    
    return A
    return B
    return C

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
string_features(S1, S2)

a. 7
b. ['F', '5', 'first']
c. ['second', '3', 'S']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [10]:
from math import log

def compute_log_loss(A):
    function_Y_Ys=0
    for i in A:
        function_Y_Ys +=(i[0]*log(i[1],10)+((1-i[0])*log(1-i[1],10)))
    Function_N=-1 * function_Y_Ys/len(A)
    return Function_N

A=[[1,0.4],[0,0.5],[0,0.9],[0,0.3],[0,0.6],[1,0.1],[1,0.9],[1,0.8]]

compute_log_loss(A)


0.42430993457031635